'use client';

import { createContext, useContext, useEffect, useState } from 'react';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from 'antd';
import enUS from 'antd/locale/en_US';
import viVN from 'antd/locale/vi_VN';
import { StoreProvider } from '@/store/StoreProvider';

const STORAGE_KEY = 'erp_logistics_language';

const dictionary = {
  en: {
    common: {
      workspace: 'Workspace',
      signOut: 'Sign out',
      exportCsv: 'Export CSV',
      exportExcel: 'Export Excel',
      resetFilters: 'Reset filters',
      refresh: 'Refresh',
      allStatuses: 'All statuses',
      searchByJobNumber: 'Search by job number',
      noDataToExport: 'There is no data to export for the current view.',
      exportSuccess: 'Exported {count} rows.',
      underPreparation: '{label} is ready for the next implementation step.'
    },
    dashboard: {
      title: 'Dashboard',
      loadError: 'Unable to load dashboard data from the backend.',
      totalJobs: 'Total Jobs',
      totalRevenue: 'Total Revenue',
      totalCost: 'Total Cost',
      profit: 'Profit'
    },
    jobs: {
      title: 'Jobs',
      subtitle: 'Manage logistics jobs from live backend data.',
      createJob: 'Create Job',
      export: 'Export',
      searchPlaceholder: 'Job number or customer',
      allStatuses: 'All statuses',
      totalLabel: 'Total',
      noJobsFound: 'No jobs found.',
      noJobsToExport: 'There are no jobs to export.',
      backendUnavailable: 'Backend data is unavailable.',
      loadError: 'Unable to load jobs from the backend.',
      exportSuccess: 'Exported {count} jobs.',
      jobNo: 'Job No.',
      customer: 'Customer',
      status: 'Status',
      origin: 'Origin',
      destination: 'Destination',
      etd: 'ETD',
      eta: 'ETA',
      shipper: 'Shipper',
      consignee: 'Consignee',
      agent: 'Agent',
      cargoType: 'Cargo Type',
      container: 'Container',
      coType: 'C/O Type',
      detail: 'Detail'
    },
    accounting: {
      chart: {
        revenueTitle: 'Revenue Trend (Monthly)',
        costTitle: 'Cost Trend (Monthly)',
        noData: 'No chart data available',
        amount: 'Amount',
        entries: 'entries'
      }
    },
    header: {
      language: 'Language',
      english: 'English',
      vietnamese: 'Vietnamese'
    },
    menu: {
      dashboard: 'Dashboard',
      jobs: 'Jobs',
      partners: 'Partners',
      accounting: 'Accounting',
      paymentRequests: 'Payment Requests',
      debtPolicies: 'Debt Policies',
      reports: 'Reports',
      pricing: 'Pricing',
      hrm: 'HRM',
      settings: 'Users & Roles',
      branches: 'Branches',
      audit: 'Audit Logs',
      navigation: 'Navigation',
      advances: 'Advances & Reimbursements',
      debitNotes: 'Debit Notes',
      cob: 'COB (Chi hộ / Thu hộ)',
      security: 'Security',
      notifications: 'Notifications',
      adjustments: 'Adjustments & Reconciliation'
    },
    login: {
      loginSuccess: 'Signed in successfully',
      loginError: 'Sign in failed. Please check your credentials.',
      loginErrorTitle: 'Login Failed',
      tryAgain: 'Try Again',
      usernameRequired: 'Please enter your username or email',
      usernamePlaceholder: 'Username or email',
      passwordRequired: 'Please enter your password',
      passwordPlaceholder: 'Password',
      forgotPassword: 'Forgot password?',
      signIn: 'Sign in',
      version: 'Version 1.0.2'
    },
    accounting: {
      breadcrumb1: 'Operations',
      breadcrumb2: 'Finance',
      breadcrumb3: 'Accounting dashboard',
      title: 'Accounting',
      subtitle: 'Track receivables, payables, and cash collection from one operational workspace.',
      revenue: 'Revenue',
      cost: 'Cost',
      revenueDescription: 'Customer invoices, payment collection, and aging.',
      costDescription: 'Vendor costs, approvals, and settlement tracking.',
      createInvoice: 'Create Invoice',
      addCostEntry: 'Add Cost Entry',
      totalRevenue: 'Total Revenue',
      totalCost: 'Total Cost',
      paidSettled: 'Paid / Settled',
      outstanding: 'Outstanding',
      draftItems: 'Draft Items',
      acrossRecords: 'Across {count} finance records',
      trackedValue: '{percent}% of tracked value',
      noPaidRecords: 'No paid records yet',
      openRecords: '{count} open records need follow-up',
      draftsExcluded: 'Drafts are excluded from settled cash flow',
      invoiceOperations: 'Invoice operations',
      recordsInView: '{count} records in view',
      pageOf: 'Page {current} of {total}',
      rowRange: '{start}-{end} of {total} records',
      noRevenueRecords: 'No revenue records match the current filters.',
      noCostRecords: 'No cost records match the current filters.',
      statusDistribution: 'Status distribution',
      statusDistributionCopy: 'A quick view of where cash flow is concentrated.',
      noChartData: 'No chart data available',
      reviewCadenceTitle: 'Review cadence',
      reviewCadenceCopy: 'Use the date range filter to review period-end collections and vendor settlement trends.',
      jobNumber: 'Job Number',
      amount: 'Amount',
      status: 'Status',
      date: 'Date',
      actions: 'Actions',
      receivableRecord: 'Receivable record',
      payableRecord: 'Payable record',
      view: 'View',
      receipt: 'Receipt',
      remind: 'Remind'
    },
    hrm: {
      title: 'Human Resources (HRM)',
      subtitle: 'Manage employee profiles, attendance, leave, and monthly payroll.',
      addEmployee: 'Add Employee',
      totalEmployees: 'Total Employees',
      activeEmployees: 'Active Employees',
      totalPayroll: 'Est. Monthly Payroll',
      employeesTab: 'Employees',
      attendanceTab: 'Attendance & Leave',
      payrollTab: 'Payroll Management',
      searchPlaceholder: 'Search name or code...',
      allDepartments: 'All Departments',
      exportExcel: 'Export Excel',
      createPayroll: 'Create Payroll',
      createPayrollBtn: 'Create Payroll',
      employee: 'Employee',
      department: 'Department',
      joinDate: 'Join Date',
      phone: 'Phone',
      status: 'Status',
      actions: 'Actions',
      viewProfile: 'View Profile',
      active: 'Active',
      onLeave: 'On Leave',
      inactive: 'Inactive',
      empCode: 'Emp Code',
      fullName: 'Full Name',
      month: 'Month',
      workDays: 'Work Days',
      leaveDays: 'Leave Days',
      absentDays: 'Absent Days',
      overtimeHrs: 'OT (hrs)',
      total: 'Total',
      baseSalary: 'Base Salary',
      allowance: 'Allowance',
      overtime: 'Overtime',
      deduction: 'Deduction',
      netSalary: 'Net Salary',
      finalized: 'Finalized',
      draft: 'Draft',
      finalizePayrollPrompt: 'Finalize this payroll?',
      finalize: 'Finalize',
      totalNetSalary: 'Total Net Salary',
      addEmpSuccess: 'Employee added successfully.',
      addEmpError: 'Failed to add employee.',
      createPayrollSuccess: 'Payroll created.',
      createPayrollError: 'Failed to create payroll.',
      finalizeSuccess: 'Payroll finalized.',
      finalizeError: 'Failed to finalize payroll.',
      loadError: 'Cannot load HRM data from backend.',
      addEmpTitle: 'Add Employee',
      position: 'Position',
      createPayrollTitle: 'Create Payroll',
      monthFormat: 'Month (YYYY-MM)',
      baseSalaryVnd: 'Base Salary (VND)',
      allowanceVnd: 'Allowance (VND)',
      otSalary: 'OT Salary',
      deductionVnd: 'Deduction (Insurance, Tax...)',
      fullNameNote: 'Full Name (Note)',
      empNamePlaceholder: 'Nguyen Van A',
      phonePlaceholder: '09xx...'
    },
    advances: {
      title: 'Advances & Reimbursements',
      subtitle: 'Manage employee advance requests and reimbursement workflows.',
      createAdvance: 'Create Advance',
      totalAdvancing: 'Total Advancing',
      pendingApproval: 'Pending Approval',
      overdueReimbursement: 'Overdue Reimbursement',
      allStatuses: 'All Statuses',
      pending: 'Pending',
      approved: 'Approved',
      settled: 'Settled',
      overdue: 'Overdue',
      rejected: 'Rejected',
      empCode: 'Emp Code',
      employee: 'Employee',
      amount: 'Amount',
      purpose: 'Purpose',
      dueDate: 'Due Date',
      status: 'Status',
      actions: 'Actions',
      reimburse: 'Reimburse',
      approveConfirm: 'Approve this advance?',
      loadError: 'Unable to load advance data from backend.',
      loadEmployeeError: 'Unable to load employee list.',
      noData: 'No advance data yet.',
      createModalTitle: 'Create Advance Request',
      employeeLabel: 'Employee',
      employeeRequired: 'Employee is required.',
      selectEmployee: 'Select employee',
      advanceAmount: 'Advance Amount',
      amountRequired: 'Amount is required.',
      currency: 'Currency',
      purposeLabel: 'Purpose',
      purposePlaceholder: 'Describe the purpose of this advance...',
      dueDateLabel: 'Due Date',
      dueDateRequired: 'Due date is required.',
      settleModalTitle: 'Confirm Reimbursement',
      settleAmount: 'Reimbursement Amount',
      notes: 'Notes',
      rejectModalTitle: 'Reject Advance',
      rejectButton: 'Reject',
      rejectReason: 'Rejection Reason',
      reasonRequired: 'Reason is required.',
      reasonPlaceholder: 'Please provide a reason...',
      createSuccess: 'Advance request created.',
      createError: 'Unable to create advance request.',
      approveSuccess: 'Advance approved.',
      approveError: 'Unable to approve advance.',
      rejectSuccess: 'Advance rejected.',
      rejectError: 'Unable to reject advance.',
      settleSuccess: 'Reimbursement completed.',
      settleError: 'Unable to complete reimbursement.'
    },
    reports: {
      title: 'Reports',
      subtitle: 'Financial and operational summaries.',
      exportExcel: 'Export Excel',
      dateRange: 'Date Range',
      exportStarted: 'Report export started.',
      exportError: 'Unable to export report.',
      loadError: 'Unable to load report data.',
      branchSummary: 'Branch Summary',
      customerSummary: 'Customer Summary',
      jobStatus: 'Job Status',
      receivables: 'Receivables',
      payables: 'Payables',
      overdueReceivables: 'Overdue Receivables',
      overduePayables: 'Overdue Payables',
      pnl: 'P&L',
      cashFlow: 'Cash Flow',
      branchId: 'Branch ID',
      customerId: 'Customer ID',
      totalRevenue: 'Total Revenue',
      totalCost: 'Total Cost',
      profit: 'Profit',
      status: 'Status',
      count: 'Count',
      paymentStatus: 'Payment Status',
      entryCount: 'Entry Count',
      totalAmount: 'Total Amount',
      entryId: 'Entry ID',
      jobId: 'Job ID',
      amount: 'Amount',
      dueDate: 'Due Date',
      period: 'Period',
      revenue: 'Revenue',
      cost: 'Cost',
      netProfit: 'Net Profit',
      totalInflow: 'Total Inflow',
      totalOutflow: 'Total Outflow',
      netCashFlow: 'Net Cash Flow'
    },
    debtPolicies: {
      title: 'Debt Policies',
      subtitle: 'Set debt limits and maximum debt age for each partner.',
      addPolicy: 'Add Policy',
      totalPolicies: 'Total Policies',
      activePolicies: 'Active Policies',
      totalDebtLimit: 'Total Debt Limit',
      loadError: 'Unable to load debt policies from the backend.',
      saveSuccess: 'Debt policy saved successfully.',
      saveError: 'Unable to save debt policy.',
      modalTitle: 'Debt Policy',
      partner: 'Partner',
      maxDebtAmount: 'Max Debt Amount',
      maxDebtAmountOptional: 'Max Debt Amount (Optional)',
      maxDebtAgeDays: 'Max Debt Age (Days)',
      maxDebtAgeDaysOptional: 'Max Debt Age in Days (Optional)',
      active: 'Active',
      inactive: 'Inactive',
      actions: 'Actions',
      status: 'Status',
      selectPartner: 'Select partner',
      partnerRequired: 'Partner is required.',
      amountPlaceholder: 'E.g., 500000000',
      daysPlaceholder: 'E.g., 30',
      notAvailable: 'N/A',
      daysSuffix: '{count} days'
    },
    paymentRequests: {
      title: 'Payment Requests',
      subtitle: 'Manage and approve vendor payment requests with a three-step workflow.',
      addRequest: 'Create Request',
      totalValue: 'Total Value',
      pendingApproval: 'Pending Approval',
      finalApproved: 'Final Approved',
      rejected: 'Rejected',
      loadError: 'Unable to load payment requests from the backend.',
      createSuccess: 'Payment request created successfully.',
      createError: 'Unable to create payment request.',
      approveSuccess: 'Payment request approved by department.',
      approveError: 'Unable to approve request.',
      finalApproveSuccess: 'Payment request final approved.',
      finalApproveError: 'Unable to final approve request.',
      rejectSuccess: 'Payment request rejected.',
      rejectError: 'Unable to reject request.',
      modalTitle: 'Create Payment Request',
      rejectModalTitle: 'Reject Payment Request',
      rejectButton: 'Reject',
      id: 'ID',
      jobVendor: 'Job / Vendor',
      amount: 'Amount',
      requestedDate: 'Req. Date',
      reason: 'Reason',
      status: 'Status',
      actions: 'Actions',
      vendor: 'Vendor',
      jobOptional: 'Job No. (Optional)',
      currency: 'Currency',
      requestedPaymentDate: 'Requested Payment Date',
      rejectionReason: 'Rejection Reason',
      provideReason: 'Provide a reason for the payment...',
      explainReject: 'Please explain why...',
      selectVendor: 'Select vendor',
      selectJob: 'Select job (if applicable)',
      vendorRequired: 'Vendor is required.',
      amountRequired: 'Amount is required.',
      reasonRequired: 'Reason is required.',
      rejectReasonRequired: 'Reason is required to reject.',
      approveConfirm: 'Approve this request?',
      finalApproveConfirm: 'Final approve this request?',
      departmentApprove: 'Department Approve',
      finalApprove: 'Final Approve',
      reject: 'Reject',
      jobLabel: 'Job: {jobNo}',
      pendingDepartmentApproval: 'Pending Approval',
      departmentApproved: 'Dept. Approved',
      rejectedStatus: 'Rejected',
      finalApprovedStatus: 'Final Approved'
    },
    debitNotes: {
      title: 'Debit Notes',
      subtitle: 'Create, post, and send debit notes to customers for services rendered on each job.',
      loadError: 'Unable to load debit notes from backend.',
      create: 'Create Debit Note',
      createTitle: 'Create Debit Note',
      createSuccess: 'Debit note created.',
      createError: 'Unable to create debit note.',
      postSuccess: 'Debit note posted.',
      postError: 'Unable to post debit note.',
      sendSuccess: 'Debit note sent to customer.',
      sendError: 'Unable to send debit note.',
      voidSuccess: 'Debit note voided.',
      voidError: 'Unable to void debit note.',
      voidTitle: 'Void Debit Note',
      voidReason: 'Void Reason',
      voidReasonRequired: 'Please provide a reason.',
      voidReasonPlaceholder: 'Why is this debit note being voided?',
      noteNo: 'DN No.',
      customer: 'Customer',
      customerRequired: 'Customer is required.',
      selectCustomer: 'Select customer',
      jobNo: 'Job No.',
      jobOptional: 'Job No. (Optional)',
      selectJob: 'Select job (if applicable)',
      amount: 'Amount',
      amountRequired: 'Amount is required.',
      currency: 'Currency',
      docDate: 'Doc Date',
      dueDate: 'Due Date',
      description: 'Description',
      descriptionPlaceholder: 'Service charges, notes...',
      status: 'Status',
      actions: 'Actions',
      totalValue: 'Total Value',
      drafts: 'Drafts',
      posted: 'Posted',
      sent: 'Sent',
      post: 'Post',
      postConfirm: 'Post this debit note?',
      send: 'Send',
      sendConfirm: 'Send this debit note to customer?',
      void: 'Void',
      serviceType: 'Service',
      lineDescription: 'Description',
      qty: 'Qty',
      unitPrice: 'Unit Price',
      lineAmount: 'Amount',
      lineItems: 'Line Items',
      addLine: 'Add Line',
      total: 'Total',
      noLineItems: 'Please add at least one line item.',
      autoApplyPricing: 'Auto-apply Pricing',
      pricingApplied: 'Applied pricing tariffs as line items.',
      noPricingFound: 'No applicable pricing tariffs found for this customer/job combination.',
      pricingHint: 'Pricing tariffs matching this customer/job',
      tariffAvailable: 'tariff(s) available',
      autoFilledFromPricing: 'Auto-filled from pricing table'
    },
    cob: {
      title: 'Charge & Collect on Behalf',
      subtitle: 'Manage charge-on-behalf (chi hộ) and collect-on-behalf (thu hộ) entries linked to jobs.',
      loadError: 'Unable to load COB data from backend.',
      chargeOnBehalf: 'Charge on Behalf',
      collectOnBehalf: 'Collect on Behalf',
      createCob: 'Create COB Entry',
      createCollect: 'Create Collect Entry',
      createCobTitle: 'Create Charge-on-Behalf',
      createCollectTitle: 'Create Collect-on-Behalf',
      createCobSuccess: 'Charge-on-behalf entry created. A receivable has been auto-generated.',
      createCobError: 'Unable to create charge-on-behalf entry.',
      createCollectSuccess: 'Collect-on-behalf entry created.',
      createCollectError: 'Unable to create collect-on-behalf entry.',
      settleSuccess: 'Entry settled.',
      settleError: 'Unable to settle entry.',
      settleConfirm: 'Settle this entry?',
      vendor: 'Vendor',
      vendorRequired: 'Vendor is required.',
      selectVendor: 'Select vendor',
      customer: 'Customer',
      customerRequired: 'Customer is required.',
      selectCustomer: 'Select customer',
      chargeToCustomer: 'Charge to Customer',
      payToVendor: 'Pay to Vendor',
      job: 'Job',
      jobOptional: 'Job No. (Optional)',
      selectJob: 'Select job (if applicable)',
      amount: 'Amount',
      amountRequired: 'Amount is required.',
      currency: 'Currency',
      description: 'Description',
      descriptionPlaceholder: 'Describe the charge...',
      status: 'Status',
      actions: 'Actions',
      totalCob: 'Total COB',
      cobPending: 'COB Pending',
      totalCollect: 'Total Collect',
      collectPending: 'Collect Pending'
    },
    notifications: {
      title: 'Notifications',
      markAllRead: 'Mark all read',
      allMarkedRead: 'All notifications marked as read.',
      markReadError: 'Unable to mark notifications as read.',
      deleteError: 'Unable to delete notification.',
      empty: 'No notifications yet.',
      inboxTitle: 'Notification Inbox',
      inboxSubtitle: 'All system alerts, workflow updates, and activity across your modules.',
      all: 'All',
      unread: 'Unread',
      read: 'Read',
      totalNotif: 'Total',
      unreadCount: 'Unread',
      deleteConfirm: 'Delete this notification?',
      markRead: 'Mark read',
      delete: 'Delete',
      historyTitle: 'Entity History',
      historySubtitle: 'Timeline of all notifications linked to this record.',
      type: 'Type',
      time: 'Time',
      message: 'Message',
      loadError: 'Unable to load notifications.'
    },
    adjustments: {
      title: 'Adjustments & Reconciliation',
      subtitle: 'Create, review, and approve adjustment entries linked to jobs.',
      createAdjustment: 'New Adjustment',
      createTitle: 'Create Adjustment Entry',
      loadError: 'Unable to load adjustments.',
      createSuccess: 'Adjustment created.',
      createError: 'Unable to create adjustment.',
      approveSuccess: 'Adjustment approved.',
      approveError: 'Unable to approve adjustment.',
      deleteSuccess: 'Adjustment deleted.',
      deleteError: 'Unable to delete adjustment.',
      deleteConfirm: 'Delete this adjustment? This cannot be undone.',
      approveConfirm: 'Approve this adjustment?',
      totalAdjustments: 'Total Adjustments',
      pendingApproval: 'Pending Approval',
      totalRevenueAdj: 'Revenue Adjustments',
      totalCostAdj: 'Cost Adjustments',
      id: 'ID',
      job: 'Job',
      type: 'Type',
      description: 'Description',
      amount: 'Amount',
      currency: 'Currency',
      status: 'Status',
      docDate: 'Doc Date',
      approvedAt: 'Approved At',
      actions: 'Actions',
      approve: 'Approve',
      delete: 'Delete',
      pending: 'Pending',
      approved: 'Approved',
      allTypes: 'All Types',
      revenueAdj: 'Revenue Adjustment',
      costAdj: 'Cost Adjustment',
      reconciliation: 'Reconciliation',
      writeOff: 'Write-Off',
      jobLabel: 'Job No.',
      jobRequired: 'Job is required.',
      typeLabel: 'Adjustment Type',
      typeRequired: 'Type is required.',
      descriptionLabel: 'Description',
      descriptionRequired: 'Description is required.',
      descriptionPlaceholder: 'Reason for adjustment...',
      amountLabel: 'Amount',
      amountRequired: 'Amount is required.',
      amountNote: 'Positive = increase, negative = decrease',
      currencyLabel: 'Currency',
      originalEntryType: 'Original Entry Type',
      originalEntryId: 'Original Entry ID',
      notesLabel: 'Notes',
      notesPlaceholder: 'Additional notes...'
    },
    security: {
      title: 'Security Center',
      subtitle: 'Monitor login activity, security alerts, and IP access rules.',
      loginEventsTab: 'Login Events',
      alertsTab: 'Security Alerts',
      ipRulesTab: 'IP Access Rules',
      loadError: 'Unable to load security data.',
      totalEvents: 'Total Events',
      openAlerts: 'Open Alerts',
      blockedLogins: 'Blocked Logins',
      activeIpRules: 'Active IP Rules',
      username: 'Username',
      status: 'Status',
      ipAddress: 'IP Address',
      riskScore: 'Risk Score',
      time: 'Time',
      alertType: 'Alert Type',
      severity: 'Severity',
      message: 'Message',
      resolvedAt: 'Resolved At',
      actions: 'Actions',
      acknowledge: 'Acknowledge',
      resolve: 'Resolve',
      acknowledgeSuccess: 'Alert acknowledged.',
      acknowledgeError: 'Unable to acknowledge alert.',
      resolveSuccess: 'Alert resolved.',
      resolveError: 'Unable to resolve alert.',
      ruleType: 'Rule Type',
      ipPattern: 'IP / Pattern',
      label: 'Label',
      description: 'Description',
      active: 'Active',
      inactive: 'Inactive',
      ruleActive: 'Active',
      addRule: 'Add Rule',
      editRule: 'Edit Rule',
      deleteRule: 'Delete',
      deleteRuleConfirm: 'Delete this IP rule?',
      createRuleTitle: 'Create IP Access Rule',
      editRuleTitle: 'Edit IP Access Rule',
      ruleTypeLabel: 'Rule Type',
      ipPatternLabel: 'IP / CIDR / Wildcard',
      ipPatternPlaceholder: 'e.g. 192.168.1.0/24 or 10.0.*',
      ruleLabel: 'Label',
      ruleLabelPlaceholder: 'e.g. Office network',
      ruleDescription: 'Description',
      ruleDescriptionPlaceholder: 'Optional notes...',
      allowType: 'ALLOW',
      blockType: 'BLOCK',
      saveRuleSuccess: 'IP rule saved.',
      saveRuleError: 'Unable to save IP rule.',
      deleteRuleSuccess: 'IP rule deleted.',
      deleteRuleError: 'Unable to delete IP rule.',
      typeRequired: 'Rule type is required.',
      ipPatternRequired: 'IP pattern is required.',
      labelRequired: 'Label is required.',
      chart: {
        revenueTitle: 'Revenue by Status',
        costTitle: 'Cost by Status',
        noData: 'No chart data available'
      }
    },
    partners: {
      title: 'Partners',
      subtitle: 'Customers, vendors, agents, and carriers used across jobs and accounting.',
      addPartner: 'Add Partner',
      editPartner: 'Edit Partner',
      createPartner: 'Create Partner',
      code: 'Code',
      name: 'Name',
      type: 'Type',
      taxCode: 'Tax Code / MST',
      contact: 'Contact',
      phone: 'Phone',
      email: 'Email',
      status: 'Status',
      actions: 'Actions',
      active: 'Active',
      inactive: 'Inactive',
      lockPartner: 'Lock partner?',
      lockDescription: 'The partner will remain in history but cannot be used as active data.',
      lock: 'Lock',
      refresh: 'Refresh',
      searchPlaceholder: 'Search code, name, tax code, phone, email',
      loadError: 'Unable to load partners from the backend.',
      saveSuccess: 'Partner saved.',
      saveError: 'Unable to save partner.',
      updateSuccess: 'Partner updated.',
      createSuccess: 'Partner created.',
      lockSuccess: 'Partner locked.',
      lockError: 'Unable to lock partner.',
      partnerCode: 'Partner Code',
      partnerCodeRequired: 'Partner code is required.',
      partnerType: 'Partner Type',
      partnerTypeRequired: 'Partner type is required.',
      partnerName: 'Name',
      partnerNameRequired: 'Partner name is required.',
      contactPerson: 'Contact Person',
      address: 'Address',
      phoneValidation: 'Enter a valid phone number.',
      emailValidation: 'Enter a valid email.',
      customer: 'Customer',
      vendor: 'Vendor',
      agent: 'Agent',
      carrier: 'Carrier',
      customerVendor: 'Customer/Vendor'
    },
    pricing: {
      title: 'Pricing & Tariffs',
      subtitle: 'Manage standard rates, carrier tariffs, and bulk Excel imports.',
      importExcel: 'Import Excel',
      addTariff: 'Add Tariff',
      addTariffTitle: 'Add New Tariff',
      activeTariffs: 'Active Tariffs',
      averageRate: 'Average Rate',
      routesCovered: 'Routes Covered',
      searchPlaceholder: 'Search by route or carrier...',
      noRecords: 'No pricing records found.',
      loadError: 'Unable to load pricing data from the backend.',
      createSuccess: 'New tariff added successfully.',
      createError: 'Unable to create service price.',
      importSuccess: 'Imported {created} new tariff(s), updated {updated}.{errorSuffix}',
      importError: 'Unable to import pricing file.',
      partner: 'Partner',
      partnerPlaceholder: 'Optional customer/vendor specific tariff',
      serviceType: 'Service Type',
      serviceTypeRequired: 'Service type is required.',
      shipmentMode: 'Shipment Mode',
      shipmentModePlaceholder: 'e.g. SEA_FCL, AIR, ROAD',
      routeFrom: 'Route From',
      routeFromPlaceholder: 'Origin / port of loading',
      routeTo: 'Route To',
      routeToPlaceholder: 'Destination / port of discharge',
      unit: 'Unit',
      unitPlaceholder: 'e.g. Container, KG, CBM',
      currency: 'Currency',
      rate: 'Rate',
      rateRequired: 'Rate is required.',
      minQuantity: 'Min Quantity',
      maxQuantity: 'Max Quantity',
      effectiveFrom: 'Effective From',
      effectiveTo: 'Effective To',
      notes: 'Notes',
      status: 'Status',
      active: 'Active',
      inactive: 'Inactive',
      route: 'Route',
      shipment: 'Shipment',
      generalTariff: 'General tariff',
      customs: 'Customs',
      trucking: 'Trucking',
      seaFreight: 'Sea Freight',
      airFreight: 'Air Freight',
      localCharge: 'Local Charge',
      lcl: 'LCL',
      other: 'Other'
    },
    users: {
      title: 'Users & Roles',
      subtitle: 'Manage accounts, role assignment, and permission groups.',
      refresh: 'Refresh',
      createUser: 'Create User',
      editUser: 'Edit User',
      createRole: 'Create Role',
      editRole: 'Edit Role',
      usersTab: 'Users',
      rolesTab: 'Roles',
      userAccounts: 'User accounts',
      permissionGroups: 'Permission groups',
      username: 'Username',
      usernameRequired: 'Username is required',
      fullName: 'Full name',
      emailLabel: 'Email',
      emailRequired: 'Valid email is required',
      branch: 'Branch',
      roles: 'Roles',
      status: 'Status',
      actions: 'Actions',
      active: 'Active',
      locked: 'Locked',
      edit: 'Edit',
      deactivate: 'Deactivate',
      deactivateConfirm: 'Deactivate this user?',
      password: 'Password',
      newPassword: 'New password',
      passwordMin: 'Password must be at least 6 characters',
      activeLabel: 'Active',
      roleName: 'Role name',
      roleNameRequired: 'Role name is required',
      description: 'Description',
      permissions: 'Permissions',
      loadError: 'Unable to load user administration data.',
      userUpdated: 'User updated.',
      userCreated: 'User created.',
      saveUserError: 'Unable to save user.',
      roleUpdated: 'Role updated.',
      roleCreated: 'Role created.',
      saveRoleError: 'Unable to save role.',
      userDeactivated: 'User deactivated.'
    },
    branches: {
      title: 'Branches',
      subtitle: 'Manage branch records and operational scope.',
      refresh: 'Refresh',
      createBranch: 'Create Branch',
      editBranch: 'Edit Branch',
      code: 'Code',
      codeRequired: 'Code is required',
      name: 'Name',
      nameRequired: 'Name is required',
      address: 'Address',
      status: 'Status',
      actions: 'Actions',
      active: 'Active',
      inactive: 'Inactive',
      activeLabel: 'Active',
      edit: 'Edit',
      loadError: 'Unable to load branches from the backend.',
      updateSuccess: 'Branch updated.',
      createSuccess: 'Branch created.',
      saveError: 'Unable to save branch.'
    },
    audit: {
      title: 'Audit Logs',
      subtitle: 'Read-only system activity trail for sensitive operations.',
      refresh: 'Refresh',
      time: 'Time',
      action: 'Action',
      entity: 'Entity',
      entityId: 'Entity ID',
      userId: 'User ID',
      ip: 'IP',
      actions: 'Actions',
      view: 'View',
      apply: 'Apply',
      reset: 'Reset',
      entityLabel: 'Entity',
      entityPlaceholder: 'jobs, partners, revenue_entries',
      entityIdLabel: 'Entity ID',
      actionLabel: 'Action',
      dateRange: 'Date range',
      loadError: 'Unable to load audit logs from the backend.',
      detailTitle: 'Audit Detail',
      ipAddress: 'IP address',
      userAgent: 'User agent',
      timestamp: 'Timestamp',
      before: 'Before',
      after: 'After'
    },
    jobForm: {
      createTitle: 'Create Job',
      detailTitle: 'Job {code}',
      breadcrumbJobs: 'Jobs',
      breadcrumbCreate: 'Create',
      breadcrumbDetail: 'Job detail',
      cancel: 'Cancel',
      createJob: 'Create Job',
      back: 'Back',
      copy: 'Copy',
      copyConfirm: 'Copy this job?',
      cancelJob: 'Cancel Job',
      cancelJobConfirm: 'Cancel this job?',
      cancelJobDescription: 'Cancelled jobs cannot be edited by the backend business rules.',
      save: 'Save',
      cardCustomer: 'Customer and Assignment',
      cardDeclaration: 'Declaration and Cargo',
      cardShipment: 'Shipment',
      cardAccounting: 'Job Accounting',
      jobNo: 'Job No.',
      jobNoRequired: 'Job No. is required.',
      jobNoPlaceholder: 'JOB-2026-0001',
      customer: 'Customer',
      customerRequired: 'Customer is required.',
      branch: 'Branch',
      assignedUser: 'Assigned User',
      shipper: 'Shipper',
      shipperPlaceholder: 'Shipper name',
      consignee: 'Consignee',
      consigneePlaceholder: 'Consignee name',
      agentCarrier: 'Agent / Carrier',
      declarationNo: 'Customs Declaration No.',
      declarationPlaceholder: 'Declaration number',
      businessType: 'Business Type',
      businessTypePlaceholder: 'Processing, production export, trading...',
      customsLane: 'Customs Lane',
      cargoType: 'Cargo Type',
      cargoTypeRequired: 'Cargo type is required.',
      containerNo: 'Container No.',
      containerPlaceholder: 'Container number',
      sealNo: 'Seal No.',
      sealPlaceholder: 'Seal number',
      notes: 'Notes',
      notesPlaceholder: 'Operational notes',
      jobType: 'Job Type',
      jobTypeRequired: 'Job type is required.',
      shipmentMode: 'Shipment Mode',
      shipmentModeRequired: 'Shipment mode is required.',
      status: 'Status',
      vessel: 'Vessel',
      voyage: 'Voyage',
      pol: 'POL',
      polPlaceholder: 'Loading port',
      pod: 'POD',
      podPlaceholder: 'Discharge port',
      origin: 'Origin',
      destination: 'Destination',
      etd: 'ETD',
      eta: 'ETA',
      atd: 'ATD',
      ata: 'ATA',
      actualDeliveryDate: 'Actual Delivery Date',
      revenue: 'Revenue',
      cost: 'Cost',
      profit: 'Profit',
      description: 'Description',
      amount: 'Amount',
      backendProfitStatus: 'Backend profit status',
      cannotVerify: 'Cannot verify from frontend only',
      missingJobId: 'Missing job id.',
      loadError: 'Unable to load this job from the backend.',
      createSuccess: 'Job created.',
      createError: 'Unable to create job.',
      updateSuccess: 'Job updated.',
      updateError: 'Unable to update job.',
      copySuccess: 'Job copied.',
      copyError: 'Unable to copy job.',
      cancelSuccess: 'Job cancelled.',
      cancelError: 'Unable to cancel job.',
      jobTypeImport: 'Import',
      jobTypeExport: 'Export',
      jobTypeDomestic: 'Domestic',
      shipmentSeaFcl: 'Sea FCL',
      shipmentSeaLcl: 'Sea LCL',
      shipmentAir: 'Air',
      shipmentRoad: 'Road',
      shipmentRail: 'Rail',
      statusDraft: 'Draft',
      statusInProgress: 'In Progress',
      statusClosed: 'Closed',
      statusCancelled: 'Cancelled',
      laneGreen: 'Green',
      laneYellow: 'Yellow',
      laneRed: 'Red',
      cargoFcl: 'FCL',
      cargoLcl: 'LCL',
      cargoAir: 'Air',
      cargoBulk: 'Bulk cargo'
    },
    accountingForm: {
      postConfirm: 'Post this draft entry?',
      postOk: 'Post',
      voidConfirm: 'Void this accounting entry?',
      voidOk: 'Void',
      markCob: 'Mark as COB',
      cobTooltip: 'Chi hộ — charge customer on behalf',
      posted: 'Posted',
      openPayment: 'Open Payment',
      draftItems: 'Draft Items',
      searchPlaceholder: 'Search job, description, status',
      noRecords: 'No accounting records found.',
      jobNo: 'Job No.',
      jobRequired: 'Job is required.',
      selectJob: 'Select job',
      vendorAgent: 'Vendor / Agent',
      vendorRequired: 'Vendor is required for cost entries.',
      selectVendor: 'Select vendor',
      description: 'Description',
      descriptionRequired: 'Description is required.',
      descriptionPlaceholder: 'Accounting description',
      currency: 'Currency',
      currencyRequired: 'Currency is required.',
      amount: 'Amount',
      amountRequired: 'Amount is required.',
      exchangeRate: 'Exchange Rate',
      exchangeRateRequired: 'Exchange rate is required.',
      localAmount: 'Local Amount',
      docDate: 'Document Date',
      dueDate: 'Due Date',
      refNumber: 'Reference No.',
      refPlaceholder: 'Reference number',
      invoiceNumber: 'Invoice No.',
      invoicePlaceholder: 'Invoice number',
      notes: 'Notes',
      notesPlaceholder: 'Notes',
      postSuccess: 'Entry posted.',
      postError: 'Unable to post entry.',
      voidSuccess: 'Entry voided.',
      voidError: 'Unable to void entry.',
      paymentUpdated: 'Payment status updated.',
      paymentError: 'Unable to update payment status.',
      cobSuccess: 'Cost marked as charge-on-behalf. A receivable has been auto-created.',
      cobError: 'Unable to create COB entry.',
      cobDescription: 'When you mark this cost as COB, the system will automatically create a matching receivable from the selected customer, linked to the same Job No.',
      selectCustomer: 'Select customer'
    },
    filterCard: {
      search: 'Search',
      status: 'Status',
      dateRange: 'Date Range',
      reset: 'Reset',
      searchPlaceholder: 'Search...'
    },
    statusTag: {
      active: 'Active',
      inactive: 'Inactive'
    },
    timeAgo: {
      justNow: 'Just now',
      minutesAgo: '{count}m ago',
      hoursAgo: '{count}h ago',
      daysAgo: '{count}d ago'
    }
  },
  vi: {
    common: {
      workspace: 'Không gian làm việc',
      signOut: 'Đăng xuất',
      exportCsv: 'Xuất CSV',
      exportExcel: 'Xuất Excel',
      resetFilters: 'Đặt lại bộ lọc',
      refresh: 'Làm mới',
      allStatuses: 'Tất cả trạng thái',
      searchByJobNumber: 'Tìm theo mã job',
      noDataToExport: 'Không có dữ liệu để xuất theo bộ lọc hiện tại.',
      exportSuccess: 'Đã xuất {count} dòng dữ liệu.',
      underPreparation: '{label} đang sẵn sàng cho bước triển khai tiếp theo.'
    },
    dashboard: {
      title: 'Bảng điều khiển',
      loadError: 'Không thể tải dữ liệu bảng điều khiển.',
      totalJobs: 'Tổng lô hàng',
      totalRevenue: 'Tổng doanh thu',
      totalCost: 'Tổng chi phí',
      profit: 'Lợi nhuận'
    },
    jobs: {
      title: 'Lô hàng',
      subtitle: 'Quản lý lô hàng logistics từ dữ liệu backend.',
      createJob: 'Tạo lô hàng',
      export: 'Xuất',
      searchPlaceholder: 'Mã lô hàng hoặc khách hàng',
      allStatuses: 'Tất cả trạng thái',
      totalLabel: 'Tổng',
      noJobsFound: 'Không tìm thấy lô hàng nào.',
      noJobsToExport: 'Không có lô hàng để xuất.',
      backendUnavailable: 'Dữ liệu backend không khả dụng.',
      loadError: 'Không thể tải lô hàng từ backend.',
      exportSuccess: 'Đã xuất {count} lô hàng.',
      jobNo: 'Mã Job',
      customer: 'Khách hàng',
      status: 'Trạng thái',
      origin: 'Điểm đi',
      destination: 'Điểm đến',
      etd: 'ETD',
      eta: 'ETA',
      shipper: 'Người gửi',
      consignee: 'Người nhận',
      agent: 'Đại lý',
      cargoType: 'Loại hàng',
      container: 'Container',
      coType: 'Loại C/O',
      detail: 'Chi tiết'
    },
    accounting: {
      chart: {
        revenueTitle: 'Biến động doanh thu (Tháng)',
        costTitle: 'Biến động chi phí (Tháng)',
        noData: 'Chưa có dữ liệu biểu đồ',
        amount: 'Số tiền',
        entries: 'bút toán'
      }
    },
    header: {
      language: 'Ngôn ngữ',
      english: 'Tiếng Anh',
      vietnamese: 'Tiếng Việt'
    },
    menu: {
      dashboard: 'Bảng điều khiển',
      jobs: 'Lô hàng',
      partners: 'Đối tác',
      accounting: 'Kế toán',
      paymentRequests: 'Yêu cầu thanh toán',
      debtPolicies: 'Chính sách công nợ',
      reports: 'Báo cáo',
      pricing: 'Bảng giá',
      hrm: 'Nhân sự (HRM)',
      settings: 'Người dùng & quyền',
      branches: 'Chi nhánh',
      audit: 'Nhật ký',
      navigation: 'Điều hướng',
      advances: 'Tạm ứng & Hoàn ứng',
      debitNotes: 'Bảng kê / Debit Note',
      cob: 'Chi hộ / Thu hộ',
      security: 'Bảo mật',
      notifications: 'Thông báo',
      adjustments: 'Điều chỉnh & Quyết toán'
    },
    login: {
      loginSuccess: 'Đăng nhập thành công',
      loginError: 'Đăng nhập thất bại. Vui lòng kiểm tra lại thông tin.',
      loginErrorTitle: 'Đăng nhập thất bại',
      tryAgain: 'Thử lại',
      usernameRequired: 'Vui lòng nhập tên đăng nhập hoặc email',
      usernamePlaceholder: 'Tên đăng nhập hoặc email',
      passwordRequired: 'Vui lòng nhập mật khẩu',
      passwordPlaceholder: 'Mật khẩu',
      forgotPassword: 'Quên mật khẩu?',
      signIn: 'Đăng nhập',
      version: 'Phiên bản 1.0.2'
    },
    accounting: {
      breadcrumb1: 'Vận hành',
      breadcrumb2: 'Tài chính',
      breadcrumb3: 'Bảng điều khiển kế toán',
      title: 'Kế toán',
      subtitle: 'Theo dõi công nợ phải thu, phải trả và dòng tiền thu chi trong một màn hình vận hành.',
      revenue: 'Doanh thu',
      cost: 'Chi phí',
      revenueDescription: 'Quản lý hóa đơn khách hàng, thu tiền và tình trạng công nợ.',
      costDescription: 'Quản lý chi phí nhà cung cấp, phê duyệt và thanh toán.',
      createInvoice: 'Tạo hóa đơn',
      addCostEntry: 'Thêm chi phí',
      totalRevenue: 'Tổng doanh thu',
      totalCost: 'Tổng chi phí',
      paidSettled: 'Đã thu / Đã thanh toán',
      outstanding: 'Còn tồn',
      draftItems: 'Bản nháp',
      acrossRecords: 'Trên {count} bút toán tài chính',
      trackedValue: '{percent}% giá trị đã được xử lý',
      noPaidRecords: 'Chưa có khoản nào đã thanh toán',
      openRecords: 'Còn {count} khoản cần theo dõi',
      draftsExcluded: 'Các bản nháp chưa được tính vào dòng tiền đã chốt',
      invoiceOperations: 'Nghiệp vụ hóa đơn',
      recordsInView: 'Có {count} dòng trong danh sách',
      pageOf: 'Trang {current} / {total}',
      rowRange: '{start}-{end} trên tổng {total} dòng',
      noRevenueRecords: 'Không có dữ liệu doanh thu phù hợp bộ lọc hiện tại.',
      noCostRecords: 'Không có dữ liệu chi phí phù hợp bộ lọc hiện tại.',
      statusDistribution: 'Phân bổ trạng thái',
      statusDistributionCopy: 'Xem nhanh giá trị đang nằm ở từng trạng thái xử lý.',
      noChartData: 'Chưa có dữ liệu biểu đồ',
      reviewCadenceTitle: 'Nhịp kiểm tra',
      reviewCadenceCopy: 'Dùng bộ lọc ngày để rà soát tình hình thu tiền và thanh toán theo từng kỳ.',
      jobNumber: 'Mã Job',
      amount: 'Số tiền',
      status: 'Trạng thái',
      date: 'Ngày',
      actions: 'Thao tác',
      receivableRecord: 'Bút toán phải thu',
      payableRecord: 'Bút toán phải trả',
      view: 'Xem',
      receipt: 'Biên nhận',
      remind: 'Nhắc việc'
    },
    hrm: {
      title: 'Nhân sự (HRM)',
      subtitle: 'Quản lý hồ sơ nhân viên, chấm công, nghỉ phép và bảng lương hàng tháng.',
      addEmployee: 'Thêm nhân viên',
      totalEmployees: 'Tổng nhân viên',
      activeEmployees: 'Đang làm việc',
      totalPayroll: 'Tổng lương tháng (ước)',
      employeesTab: 'Nhân viên',
      attendanceTab: 'Chấm công & Nghỉ phép',
      payrollTab: 'Quản lý Lương',
      searchPlaceholder: 'Tìm theo tên hoặc mã NV...',
      allDepartments: 'Tất cả bộ phận',
      exportExcel: 'Xuất Excel',
      createPayroll: 'Tạo bảng lương',
      createPayrollBtn: 'Tạo bảng lương',
      employee: 'Nhân viên',
      department: 'Bộ phận',
      joinDate: 'Ngày vào làm',
      phone: 'SĐT',
      status: 'Trạng thái',
      actions: 'Thao tác',
      viewProfile: 'Xem hồ sơ',
      active: 'Đang làm',
      onLeave: 'Nghỉ phép',
      inactive: 'Nghỉ việc',
      empCode: 'Mã NV',
      fullName: 'Họ tên',
      month: 'Tháng',
      workDays: 'Ngày công',
      leaveDays: 'Nghỉ phép',
      absentDays: 'Vắng',
      overtimeHrs: 'OT (giờ)',
      total: 'Tổng cộng',
      baseSalary: 'Lương cơ bản',
      allowance: 'Phụ cấp',
      overtime: 'OT',
      deduction: 'Khấu trừ',
      netSalary: 'Thực lĩnh',
      finalized: 'Đã chốt',
      draft: 'Nháp',
      finalizePayrollPrompt: 'Chốt bảng lương này?',
      finalize: 'Chốt',
      totalNetSalary: 'Tổng thực lĩnh',
      addEmpSuccess: 'Đã thêm nhân viên thành công.',
      addEmpError: 'Không thể lưu nhân viên.',
      createPayrollSuccess: 'Đã tạo bảng lương.',
      createPayrollError: 'Không thể tạo bảng lương.',
      finalizeSuccess: 'Đã chốt bảng lương.',
      finalizeError: 'Không thể chốt bảng lương.',
      loadError: 'Không thể tải dữ liệu HRM từ backend.',
      addEmpTitle: 'Thêm nhân viên',
      position: 'Chức vụ',
      createPayrollTitle: 'Tạo bảng lương',
      monthFormat: 'Tháng (YYYY-MM)',
      baseSalaryVnd: 'Lương cơ bản (VND)',
      allowanceVnd: 'Phụ cấp (VND)',
      otSalary: 'Lương OT',
      deductionVnd: 'Khấu trừ (BHXH, thuế...)',
      fullNameNote: 'Họ tên (ghi chú)',
      empNamePlaceholder: 'Nguyễn Văn A',
      phonePlaceholder: '09xx...'
    },
    advances: {
      title: 'Tạm ứng & Hoàn ứng',
      subtitle: 'Quản lý quy trình nhân viên tạm ứng và hoàn ứng.',
      createAdvance: 'Tạo tạm ứng',
      totalAdvancing: 'Tổng đang tạm ứng',
      pendingApproval: 'Chờ duyệt',
      overdueReimbursement: 'Quá hạn hoàn ứng',
      allStatuses: 'Tất cả trạng thái',
      pending: 'Chờ duyệt',
      approved: 'Đã duyệt',
      settled: 'Đã hoàn ứng',
      overdue: 'Quá hạn',
      rejected: 'Từ chối',
      empCode: 'Mã NV',
      employee: 'Nhân viên',
      amount: 'Số tiền',
      purpose: 'Mục đích',
      dueDate: 'Hạn hoàn ứng',
      status: 'Trạng thái',
      actions: 'Thao tác',
      reimburse: 'Hoàn ứng',
      approveConfirm: 'Duyệt tạm ứng này?',
      loadError: 'Không thể tải dữ liệu tạm ứng từ backend.',
      loadEmployeeError: 'Không thể tải danh sách nhân viên.',
      noData: 'Chưa có dữ liệu tạm ứng.',
      createModalTitle: 'Tạo yêu cầu tạm ứng',
      employeeLabel: 'Nhân viên',
      employeeRequired: 'Nhân viên là bắt buộc.',
      selectEmployee: 'Chọn nhân viên',
      advanceAmount: 'Số tiền tạm ứng',
      amountRequired: 'Số tiền là bắt buộc.',
      currency: 'Đơn vị tiền tệ',
      purposeLabel: 'Mục đích sử dụng',
      purposePlaceholder: 'Ghi rõ mục đích tạm ứng...',
      dueDateLabel: 'Hạn hoàn ứng',
      dueDateRequired: 'Hạn hoàn ứng là bắt buộc.',
      settleModalTitle: 'Xác nhận hoàn ứng',
      settleAmount: 'Số tiền hoàn ứng',
      notes: 'Ghi chú',
      rejectModalTitle: 'Từ chối tạm ứng',
      rejectButton: 'Từ chối',
      rejectReason: 'Lý do từ chối',
      reasonRequired: 'Lý do là bắt buộc.',
      reasonPlaceholder: 'Vui lòng ghi rõ lý do...',
      createSuccess: 'Đã tạo yêu cầu tạm ứng.',
      createError: 'Không thể tạo yêu cầu tạm ứng.',
      approveSuccess: 'Đã duyệt tạm ứng.',
      approveError: 'Không thể duyệt tạm ứng.',
      rejectSuccess: 'Đã từ chối tạm ứng.',
      rejectError: 'Không thể từ chối tạm ứng.',
      settleSuccess: 'Đã hoàn ứng thành công.',
      settleError: 'Không thể hoàn ứng.'
    },
    reports: {
      title: 'Báo cáo',
      subtitle: 'Tổng hợp tài chính và vận hành.',
      exportExcel: 'Xuất Excel',
      dateRange: 'Khoảng ngày',
      exportStarted: 'Đã bắt đầu xuất báo cáo.',
      exportError: 'Không thể xuất báo cáo.',
      loadError: 'Không thể tải dữ liệu báo cáo.',
      branchSummary: 'Tổng hợp chi nhánh',
      customerSummary: 'Tổng hợp khách hàng',
      jobStatus: 'Trạng thái job',
      receivables: 'Phải thu',
      payables: 'Phải trả',
      overdueReceivables: 'Phải thu quá hạn',
      overduePayables: 'Phải trả quá hạn',
      pnl: 'Lãi lỗ',
      cashFlow: 'Dòng tiền',
      branchId: 'Mã chi nhánh',
      customerId: 'Mã khách hàng',
      totalRevenue: 'Tổng doanh thu',
      totalCost: 'Tổng chi phí',
      profit: 'Lợi nhuận',
      status: 'Trạng thái',
      count: 'Số lượng',
      paymentStatus: 'Trạng thái thanh toán',
      entryCount: 'Số bút toán',
      totalAmount: 'Tổng số tiền',
      entryId: 'Mã bút toán',
      jobId: 'Mã job',
      amount: 'Số tiền',
      dueDate: 'Ngày đến hạn',
      period: 'Kỳ',
      revenue: 'Doanh thu',
      cost: 'Chi phí',
      netProfit: 'Lợi nhuận thuần',
      totalInflow: 'Tổng tiền vào',
      totalOutflow: 'Tổng tiền ra',
      netCashFlow: 'Dòng tiền thuần'
    },
    debtPolicies: {
      title: 'Chính sách công nợ',
      subtitle: 'Thiết lập giới hạn công nợ và số ngày nợ tối đa cho từng đối tác.',
      addPolicy: 'Thêm chính sách',
      totalPolicies: 'Tổng chính sách',
      activePolicies: 'Đang áp dụng',
      totalDebtLimit: 'Tổng hạn mức công nợ',
      loadError: 'Không thể tải chính sách công nợ từ backend.',
      saveSuccess: 'Đã lưu chính sách công nợ.',
      saveError: 'Không thể lưu chính sách công nợ.',
      modalTitle: 'Chính sách công nợ',
      partner: 'Đối tác',
      maxDebtAmount: 'Hạn mức công nợ',
      maxDebtAmountOptional: 'Hạn mức công nợ (Tùy chọn)',
      maxDebtAgeDays: 'Số ngày nợ tối đa',
      maxDebtAgeDaysOptional: 'Số ngày nợ tối đa (Tùy chọn)',
      active: 'Đang áp dụng',
      inactive: 'Ngừng áp dụng',
      actions: 'Thao tác',
      status: 'Trạng thái',
      selectPartner: 'Chọn đối tác',
      partnerRequired: 'Vui lòng chọn đối tác.',
      amountPlaceholder: 'Ví dụ: 500000000',
      daysPlaceholder: 'Ví dụ: 30',
      notAvailable: 'Không áp dụng',
      daysSuffix: '{count} ngày'
    },
    paymentRequests: {
      title: 'Yêu cầu thanh toán',
      subtitle: 'Quản lý và duyệt yêu cầu thanh toán nhà cung cấp theo luồng 3 bước.',
      addRequest: 'Tạo yêu cầu',
      totalValue: 'Tổng giá trị',
      pendingApproval: 'Chờ duyệt',
      finalApproved: 'Đã duyệt cuối',
      rejected: 'Từ chối',
      loadError: 'Không thể tải yêu cầu thanh toán từ backend.',
      createSuccess: 'Đã tạo yêu cầu thanh toán.',
      createError: 'Không thể tạo yêu cầu thanh toán.',
      approveSuccess: 'Đã duyệt yêu cầu ở cấp phòng ban.',
      approveError: 'Không thể duyệt yêu cầu.',
      finalApproveSuccess: 'Đã duyệt cuối yêu cầu thanh toán.',
      finalApproveError: 'Không thể duyệt cuối yêu cầu.',
      rejectSuccess: 'Đã từ chối yêu cầu thanh toán.',
      rejectError: 'Không thể từ chối yêu cầu.',
      modalTitle: 'Tạo yêu cầu thanh toán',
      rejectModalTitle: 'Từ chối yêu cầu thanh toán',
      rejectButton: 'Từ chối',
      id: 'Mã',
      jobVendor: 'Job / Nhà cung cấp',
      amount: 'Số tiền',
      requestedDate: 'Ngày yêu cầu',
      reason: 'Lý do',
      status: 'Trạng thái',
      actions: 'Thao tác',
      vendor: 'Nhà cung cấp',
      jobOptional: 'Mã Job (Tùy chọn)',
      currency: 'Tiền tệ',
      requestedPaymentDate: 'Ngày đề nghị thanh toán',
      rejectionReason: 'Lý do từ chối',
      provideReason: 'Nhập lý do thanh toán...',
      explainReject: 'Vui lòng giải thích lý do...',
      selectVendor: 'Chọn nhà cung cấp',
      selectJob: 'Chọn job (nếu có)',
      vendorRequired: 'Vui lòng chọn nhà cung cấp.',
      amountRequired: 'Vui lòng nhập số tiền.',
      reasonRequired: 'Vui lòng nhập lý do.',
      rejectReasonRequired: 'Cần nhập lý do để từ chối.',
      approveConfirm: 'Duyệt yêu cầu này?',
      finalApproveConfirm: 'Duyệt cuối yêu cầu này?',
      departmentApprove: 'Duyệt phòng ban',
      finalApprove: 'Duyệt cuối',
      reject: 'Từ chối',
      jobLabel: 'Job: {jobNo}',
      pendingDepartmentApproval: 'Chờ duyệt',
      departmentApproved: 'Đã duyệt phòng ban',
      rejectedStatus: 'Từ chối',
      finalApprovedStatus: 'Đã duyệt cuối'
    },
    debitNotes: {
      title: 'Bảng kê / Debit Note',
      subtitle: 'Tạo, chốt và gửi bảng kê cho khách hàng theo từng lô hàng.',
      loadError: 'Không thể tải danh sách bảng kê từ backend.',
      create: 'Tạo bảng kê',
      createTitle: 'Tạo bảng kê mới',
      createSuccess: 'Đã tạo bảng kê.',
      createError: 'Không thể tạo bảng kê.',
      postSuccess: 'Đã chốt bảng kê.',
      postError: 'Không thể chốt bảng kê.',
      sendSuccess: 'Đã gửi bảng kê cho khách hàng.',
      sendError: 'Không thể gửi bảng kê.',
      voidSuccess: 'Đã hủy bảng kê.',
      voidError: 'Không thể hủy bảng kê.',
      voidTitle: 'Hủy bảng kê',
      voidReason: 'Lý do hủy',
      voidReasonRequired: 'Vui lòng ghi rõ lý do.',
      voidReasonPlaceholder: 'Tại sao hủy bảng kê này?',
      noteNo: 'Số DN',
      customer: 'Khách hàng',
      customerRequired: 'Vui lòng chọn khách hàng.',
      selectCustomer: 'Chọn khách hàng',
      jobNo: 'Mã Job',
      jobOptional: 'Mã Job (Tùy chọn)',
      selectJob: 'Chọn job (nếu có)',
      amount: 'Số tiền',
      amountRequired: 'Vui lòng nhập số tiền.',
      currency: 'Tiền tệ',
      docDate: 'Ngày chứng từ',
      dueDate: 'Ngày đến hạn',
      description: 'Mô tả',
      descriptionPlaceholder: 'Phí dịch vụ, ghi chú...',
      status: 'Trạng thái',
      actions: 'Thao tác',
      totalValue: 'Tổng giá trị',
      drafts: 'Bản nháp',
      posted: 'Đã chốt',
      sent: 'Đã gửi',
      post: 'Chốt',
      postConfirm: 'Chốt bảng kê này?',
      send: 'Gửi',
      sendConfirm: 'Gửi bảng kê cho khách hàng?',
      void: 'Hủy',
      serviceType: 'Dịch vụ',
      lineDescription: 'Mô tả',
      qty: 'SL',
      unitPrice: 'Đơn giá',
      lineAmount: 'Thành tiền',
      lineItems: 'Chi tiết dịch vụ',
      addLine: 'Thêm dòng',
      total: 'Tổng cộng',
      noLineItems: 'Vui lòng thêm ít nhất một dòng dịch vụ.',
      autoApplyPricing: 'Áp giá tự động',
      pricingApplied: 'Đã áp giá từ bảng giá.',
      noPricingFound: 'Không tìm thấy biểu giá phù hợp cho khách hàng/lô hàng này.',
      pricingHint: 'Biểu giá phù hợp cho khách hàng/lô hàng',
      tariffAvailable: 'biểu giá khả dụng',
      autoFilledFromPricing: 'Tự động áp từ bảng giá'
    },
    cob: {
      title: 'Chi hộ & Thu hộ',
      subtitle: 'Quản lý các khoản chi hộ và thu hộ liên kết theo từng lô hàng.',
      loadError: 'Không thể tải dữ liệu chi hộ/thu hộ từ backend.',
      chargeOnBehalf: 'Chi hộ',
      collectOnBehalf: 'Thu hộ',
      createCob: 'Tạo chi hộ',
      createCollect: 'Tạo thu hộ',
      createCobTitle: 'Tạo khoản chi hộ',
      createCollectTitle: 'Tạo khoản thu hộ',
      createCobSuccess: 'Đã tạo khoản chi hộ. Phải thu tự động đã được tạo.',
      createCobError: 'Không thể tạo khoản chi hộ.',
      createCollectSuccess: 'Đã tạo khoản thu hộ.',
      createCollectError: 'Không thể tạo khoản thu hộ.',
      settleSuccess: 'Đã tất toán.',
      settleError: 'Không thể tất toán.',
      settleConfirm: 'Tất toán khoản này?',
      vendor: 'Nhà cung cấp',
      vendorRequired: 'Vui lòng chọn NCC.',
      selectVendor: 'Chọn nhà cung cấp',
      customer: 'Khách hàng',
      customerRequired: 'Vui lòng chọn khách hàng.',
      selectCustomer: 'Chọn khách hàng',
      chargeToCustomer: 'Tính phí cho khách hàng',
      payToVendor: 'Thanh toán cho NCC',
      job: 'Lô hàng',
      jobOptional: 'Mã Job (Tùy chọn)',
      selectJob: 'Chọn job (nếu có)',
      amount: 'Số tiền',
      amountRequired: 'Vui lòng nhập số tiền.',
      currency: 'Tiền tệ',
      description: 'Mô tả',
      descriptionPlaceholder: 'Mô tả khoản chi/thu...',
      status: 'Trạng thái',
      actions: 'Thao tác',
      totalCob: 'Tổng chi hộ',
      cobPending: 'Chi hộ chưa TT',
      totalCollect: 'Tổng thu hộ',
      collectPending: 'Thu hộ chưa TT'
    },
    notifications: {
      title: 'Thông báo',
      markAllRead: 'Đánh dấu tất cả đã đọc',
      allMarkedRead: 'Đã đánh dấu tất cả thông báo là đã đọc.',
      markReadError: 'Không thể đánh dấu thông báo.',
      deleteError: 'Không thể xóa thông báo.',
      empty: 'Chưa có thông báo nào.',
      inboxTitle: 'Hộp thư thông báo',
      inboxSubtitle: 'Tất cả cảnh báo hệ thống, cập nhật quy trình và hoạt động trong các phân hệ.',
      all: 'Tất cả',
      unread: 'Chưa đọc',
      read: 'Đã đọc',
      totalNotif: 'Tổng số',
      unreadCount: 'Chưa đọc',
      deleteConfirm: 'Xóa thông báo này?',
      markRead: 'Đánh dấu đã đọc',
      delete: 'Xóa',
      historyTitle: 'Lịch sử hoạt động',
      historySubtitle: 'Toàn bộ thông báo liên kết đến bản ghi này.',
      type: 'Loại',
      time: 'Thời gian',
      message: 'Nội dung',
      loadError: 'Không thể tải thông báo.'
    },
    adjustments: {
      title: 'Điều chỉnh & Quyết toán',
      subtitle: 'Tạo, xem xét và phê duyệt các bút toán điều chỉnh theo từng lô hàng.',
      createAdjustment: 'Tạo điều chỉnh',
      createTitle: 'Tạo bút toán điều chỉnh',
      loadError: 'Không thể tải dữ liệu điều chỉnh.',
      createSuccess: 'Đã tạo điều chỉnh.',
      createError: 'Không thể tạo điều chỉnh.',
      approveSuccess: 'Đã duyệt điều chỉnh.',
      approveError: 'Không thể duyệt điều chỉnh.',
      deleteSuccess: 'Đã xóa điều chỉnh.',
      deleteError: 'Không thể xóa điều chỉnh.',
      deleteConfirm: 'Xóa điều chỉnh này? Không thể hoàn tác.',
      approveConfirm: 'Duyệt điều chỉnh này?',
      totalAdjustments: 'Tổng điều chỉnh',
      pendingApproval: 'Chờ duyệt',
      totalRevenueAdj: 'ĐC doanh thu',
      totalCostAdj: 'ĐC chi phí',
      id: 'Mã',
      job: 'Lô hàng',
      type: 'Loại',
      description: 'Mô tả',
      amount: 'Số tiền',
      currency: 'Tiền tệ',
      status: 'Trạng thái',
      docDate: 'Ngày chứng từ',
      approvedAt: 'Đã duyệt lúc',
      actions: 'Thao tác',
      approve: 'Duyệt',
      delete: 'Xóa',
      pending: 'Chờ duyệt',
      approved: 'Đã duyệt',
      allTypes: 'Tất cả loại',
      revenueAdj: 'ĐC doanh thu',
      costAdj: 'ĐC chi phí',
      reconciliation: 'Quyết toán',
      writeOff: 'Xóa nợ',
      jobLabel: 'Mã Job',
      jobRequired: 'Vui lòng chọn job.',
      typeLabel: 'Loại điều chỉnh',
      typeRequired: 'Loại là bắt buộc.',
      descriptionLabel: 'Mô tả',
      descriptionRequired: 'Mô tả là bắt buộc.',
      descriptionPlaceholder: 'Lý do điều chỉnh...',
      amountLabel: 'Số tiền',
      amountRequired: 'Số tiền là bắt buộc.',
      amountNote: 'Dương = tăng, âm = giảm',
      currencyLabel: 'Tiền tệ',
      originalEntryType: 'Loại bút toán gốc',
      originalEntryId: 'Mã bút toán gốc',
      notesLabel: 'Ghi chú',
      notesPlaceholder: 'Ghi chú thêm...'
    },
    security: {
      title: 'Trung tâm Bảo mật',
      subtitle: 'Giám sát hoạt động đăng nhập, cảnh báo bảo mật và quy tắc IP.',
      loginEventsTab: 'Nhật ký đăng nhập',
      alertsTab: 'Cảnh báo bảo mật',
      ipRulesTab: 'Quy tắc IP',
      loadError: 'Không thể tải dữ liệu bảo mật.',
      totalEvents: 'Tổng sự kiện',
      openAlerts: 'Cảnh báo mở',
      blockedLogins: 'Đăng nhập bị chặn',
      activeIpRules: 'Quy tắc IP đang hoạt động',
      username: 'Tên đăng nhập',
      status: 'Trạng thái',
      ipAddress: 'Địa chỉ IP',
      riskScore: 'Điểm rủi ro',
      time: 'Thời gian',
      alertType: 'Loại cảnh báo',
      severity: 'Mức độ',
      message: 'Thông điệp',
      resolvedAt: 'Đã giải quyết lúc',
      actions: 'Thao tác',
      acknowledge: 'Xác nhận',
      resolve: 'Giải quyết',
      acknowledgeSuccess: 'Đã xác nhận cảnh báo.',
      acknowledgeError: 'Không thể xác nhận cảnh báo.',
      resolveSuccess: 'Đã giải quyết cảnh báo.',
      resolveError: 'Không thể giải quyết cảnh báo.',
      ruleType: 'Loại quy tắc',
      ipPattern: 'IP / Pattern',
      label: 'Nhãn',
      description: 'Mô tả',
      active: 'Đang hoạt động',
      inactive: 'Không hoạt động',
      ruleActive: 'Đang hoạt động',
      addRule: 'Thêm quy tắc',
      editRule: 'Sửa quy tắc',
      deleteRule: 'Xóa',
      deleteRuleConfirm: 'Xóa quy tắc IP này?',
      createRuleTitle: 'Tạo quy tắc IP',
      editRuleTitle: 'Sửa quy tắc IP',
      ruleTypeLabel: 'Loại quy tắc',
      ipPatternLabel: 'IP / CIDR / Wildcard',
      ipPatternPlaceholder: 'Ví dụ: 192.168.1.0/24 hoặc 10.0.*',
      ruleLabel: 'Nhãn',
      ruleLabelPlaceholder: 'Ví dụ: Mạng văn phòng',
      ruleDescription: 'Mô tả',
      ruleDescriptionPlaceholder: 'Ghi chú tùy chọn...',
      allowType: 'CHO PHÉP',
      blockType: 'CHẶN',
      saveRuleSuccess: 'Đã lưu quy tắc IP.',
      saveRuleError: 'Không thể lưu quy tắc IP.',
      deleteRuleSuccess: 'Đã xóa quy tắc IP.',
      deleteRuleError: 'Không thể xóa quy tắc IP.',
      typeRequired: 'Loại quy tắc là bắt buộc.',
      ipPatternRequired: 'IP pattern là bắt buộc.',
      labelRequired: 'Nhãn là bắt buộc.',
      chart: {
        revenueTitle: 'Doanh thu theo trạng thái',
        costTitle: 'Chi phí theo trạng thái',
        noData: 'Chưa có dữ liệu biểu đồ'
      }
    },
    partners: {
      title: 'Đối tác',
      subtitle: 'Khách hàng, nhà cung cấp, đại lý và hãng vận tải sử dụng trong job và kế toán.',
      addPartner: 'Thêm đối tác',
      editPartner: 'Sửa đối tác',
      createPartner: 'Tạo đối tác',
      code: 'Mã',
      name: 'Tên',
      type: 'Loại',
      taxCode: 'MST',
      contact: 'Liên hệ',
      phone: 'SĐT',
      email: 'Email',
      status: 'Trạng thái',
      actions: 'Thao tác',
      active: 'Hoạt động',
      inactive: 'Ngừng HĐ',
      lockPartner: 'Khóa đối tác?',
      lockDescription: 'Đối tác sẽ vẫn tồn tại trong lịch sử nhưng không thể sử dụng làm dữ liệu hoạt động.',
      lock: 'Khóa',
      refresh: 'Làm mới',
      searchPlaceholder: 'Tìm theo mã, tên, MST, SĐT, email',
      loadError: 'Không thể tải danh sách đối tác từ backend.',
      saveSuccess: 'Đã lưu đối tác.',
      saveError: 'Không thể lưu đối tác.',
      updateSuccess: 'Đã cập nhật đối tác.',
      createSuccess: 'Đã tạo đối tác.',
      lockSuccess: 'Đã khóa đối tác.',
      lockError: 'Không thể khóa đối tác.',
      partnerCode: 'Mã đối tác',
      partnerCodeRequired: 'Mã đối tác là bắt buộc.',
      partnerType: 'Loại đối tác',
      partnerTypeRequired: 'Loại đối tác là bắt buộc.',
      partnerName: 'Tên',
      partnerNameRequired: 'Tên đối tác là bắt buộc.',
      contactPerson: 'Người liên hệ',
      address: 'Địa chỉ',
      phoneValidation: 'Vui lòng nhập số điện thoại hợp lệ.',
      emailValidation: 'Vui lòng nhập email hợp lệ.',
      customer: 'Khách hàng',
      vendor: 'Nhà cung cấp',
      agent: 'Đại lý',
      carrier: 'Hãng vận tải',
      customerVendor: 'Khách hàng/NCC'
    },
    pricing: {
      title: 'Bảng giá & Biểu phí',
      subtitle: 'Quản lý biểu giá tiêu chuẩn, giá hãng tàu và nhập Excel hàng loạt.',
      importExcel: 'Nhập Excel',
      addTariff: 'Thêm biểu giá',
      addTariffTitle: 'Thêm biểu giá mới',
      activeTariffs: 'Biểu giá đang áp dụng',
      averageRate: 'Giá trung bình',
      routesCovered: 'Tuyến đường',
      searchPlaceholder: 'Tìm theo tuyến đường hoặc hãng...',
      noRecords: 'Không tìm thấy biểu giá nào.',
      loadError: 'Không thể tải dữ liệu bảng giá từ backend.',
      createSuccess: 'Đã thêm biểu giá mới.',
      createError: 'Không thể tạo biểu giá.',
      importSuccess: 'Đã nhập {created} biểu giá mới, cập nhật {updated}.{errorSuffix}',
      importError: 'Không thể nhập file bảng giá.',
      partner: 'Đối tác',
      partnerPlaceholder: 'Biểu giá riêng cho khách hàng/NCC (tùy chọn)',
      serviceType: 'Loại dịch vụ',
      serviceTypeRequired: 'Loại dịch vụ là bắt buộc.',
      shipmentMode: 'Phương thức vận chuyển',
      shipmentModePlaceholder: 'VD: SEA_FCL, AIR, ROAD',
      routeFrom: 'Nơi đi',
      routeFromPlaceholder: 'Điểm xuất phát / cảng xếp',
      routeTo: 'Nơi đến',
      routeToPlaceholder: 'Điểm đến / cảng dỡ',
      unit: 'Đơn vị',
      unitPlaceholder: 'VD: Container, KG, CBM',
      currency: 'Tiền tệ',
      rate: 'Đơn giá',
      rateRequired: 'Đơn giá là bắt buộc.',
      minQuantity: 'SL tối thiểu',
      maxQuantity: 'SL tối đa',
      effectiveFrom: 'Hiệu lực từ',
      effectiveTo: 'Hiệu lực đến',
      notes: 'Ghi chú',
      status: 'Trạng thái',
      active: 'Đang áp dụng',
      inactive: 'Ngừng áp dụng',
      route: 'Tuyến đường',
      shipment: 'Vận chuyển',
      generalTariff: 'Biểu giá chung',
      customs: 'Hải quan',
      trucking: 'Vận tải đường bộ',
      seaFreight: 'Cước biển',
      airFreight: 'Cước hàng không',
      localCharge: 'Phí nội địa',
      lcl: 'LCL',
      other: 'Khác'
    },
    users: {
      title: 'Người dùng & Quyền',
      subtitle: 'Quản lý tài khoản, phân quyền và nhóm quyền.',
      refresh: 'Làm mới',
      createUser: 'Tạo người dùng',
      editUser: 'Sửa người dùng',
      createRole: 'Tạo vai trò',
      editRole: 'Sửa vai trò',
      usersTab: 'Người dùng',
      rolesTab: 'Vai trò',
      userAccounts: 'Tài khoản người dùng',
      permissionGroups: 'Nhóm quyền',
      username: 'Tên đăng nhập',
      usernameRequired: 'Tên đăng nhập là bắt buộc',
      fullName: 'Họ tên',
      emailLabel: 'Email',
      emailRequired: 'Vui lòng nhập email hợp lệ',
      branch: 'Chi nhánh',
      roles: 'Vai trò',
      status: 'Trạng thái',
      actions: 'Thao tác',
      active: 'Hoạt động',
      locked: 'Đã khóa',
      edit: 'Sửa',
      deactivate: 'Vô hiệu hóa',
      deactivateConfirm: 'Vô hiệu hóa người dùng này?',
      password: 'Mật khẩu',
      newPassword: 'Mật khẩu mới',
      passwordMin: 'Mật khẩu phải có ít nhất 6 ký tự',
      activeLabel: 'Kích hoạt',
      roleName: 'Tên vai trò',
      roleNameRequired: 'Tên vai trò là bắt buộc',
      description: 'Mô tả',
      permissions: 'Quyền',
      loadError: 'Không thể tải dữ liệu quản trị người dùng.',
      userUpdated: 'Đã cập nhật người dùng.',
      userCreated: 'Đã tạo người dùng.',
      saveUserError: 'Không thể lưu người dùng.',
      roleUpdated: 'Đã cập nhật vai trò.',
      roleCreated: 'Đã tạo vai trò.',
      saveRoleError: 'Không thể lưu vai trò.',
      userDeactivated: 'Đã vô hiệu hóa người dùng.'
    },
    branches: {
      title: 'Chi nhánh',
      subtitle: 'Quản lý chi nhánh và phạm vi hoạt động.',
      refresh: 'Làm mới',
      createBranch: 'Tạo chi nhánh',
      editBranch: 'Sửa chi nhánh',
      code: 'Mã',
      codeRequired: 'Mã chi nhánh là bắt buộc',
      name: 'Tên',
      nameRequired: 'Tên chi nhánh là bắt buộc',
      address: 'Địa chỉ',
      status: 'Trạng thái',
      actions: 'Thao tác',
      active: 'Hoạt động',
      inactive: 'Ngừng HĐ',
      activeLabel: 'Kích hoạt',
      edit: 'Sửa',
      loadError: 'Không thể tải danh sách chi nhánh từ backend.',
      updateSuccess: 'Đã cập nhật chi nhánh.',
      createSuccess: 'Đã tạo chi nhánh.',
      saveError: 'Không thể lưu chi nhánh.'
    },
    audit: {
      title: 'Nhật ký hệ thống',
      subtitle: 'Theo dõi lịch sử thao tác trên hệ thống (chỉ xem).',
      refresh: 'Làm mới',
      time: 'Thời gian',
      action: 'Hành động',
      entity: 'Đối tượng',
      entityId: 'Mã đối tượng',
      userId: 'Mã người dùng',
      ip: 'IP',
      actions: 'Thao tác',
      view: 'Xem',
      apply: 'Áp dụng',
      reset: 'Đặt lại',
      entityLabel: 'Đối tượng',
      entityPlaceholder: 'jobs, partners, revenue_entries',
      entityIdLabel: 'Mã đối tượng',
      actionLabel: 'Hành động',
      dateRange: 'Khoảng ngày',
      loadError: 'Không thể tải nhật ký từ backend.',
      detailTitle: 'Chi tiết nhật ký',
      ipAddress: 'Địa chỉ IP',
      userAgent: 'Trình duyệt',
      timestamp: 'Thời điểm',
      before: 'Trước',
      after: 'Sau'
    },
    jobForm: {
      createTitle: 'Tạo lô hàng',
      detailTitle: 'Job {code}',
      breadcrumbJobs: 'Lô hàng',
      breadcrumbCreate: 'Tạo mới',
      breadcrumbDetail: 'Chi tiết job',
      cancel: 'Hủy',
      createJob: 'Tạo lô hàng',
      back: 'Quay lại',
      copy: 'Sao chép',
      copyConfirm: 'Sao chép job này?',
      cancelJob: 'Hủy job',
      cancelJobConfirm: 'Hủy job này?',
      cancelJobDescription: 'Job đã hủy sẽ không thể chỉnh sửa theo quy tắc nghiệp vụ.',
      save: 'Lưu',
      cardCustomer: 'Khách hàng & Phân công',
      cardDeclaration: 'Tờ khai & Hàng hóa',
      cardShipment: 'Vận chuyển',
      cardAccounting: 'Kế toán Job',
      jobNo: 'Mã Job',
      jobNoRequired: 'Mã Job là bắt buộc.',
      jobNoPlaceholder: 'JOB-2026-0001',
      customer: 'Khách hàng',
      customerRequired: 'Khách hàng là bắt buộc.',
      branch: 'Chi nhánh',
      assignedUser: 'Người phụ trách',
      shipper: 'Người gửi',
      shipperPlaceholder: 'Tên người gửi',
      consignee: 'Người nhận',
      consigneePlaceholder: 'Tên người nhận',
      agentCarrier: 'Đại lý / Hãng vận tải',
      declarationNo: 'Số tờ khai hải quan',
      declarationPlaceholder: 'Số tờ khai',
      businessType: 'Loại hình kinh doanh',
      businessTypePlaceholder: 'Gia công, sản xuất XK, thương mại...',
      customsLane: 'Luồng hải quan',
      cargoType: 'Loại hàng',
      cargoTypeRequired: 'Loại hàng là bắt buộc.',
      containerNo: 'Số container',
      containerPlaceholder: 'Số container',
      sealNo: 'Số seal',
      sealPlaceholder: 'Số seal',
      notes: 'Ghi chú',
      notesPlaceholder: 'Ghi chú vận hành',
      jobType: 'Loại job',
      jobTypeRequired: 'Loại job là bắt buộc.',
      shipmentMode: 'Phương thức vận chuyển',
      shipmentModeRequired: 'Phương thức VC là bắt buộc.',
      status: 'Trạng thái',
      vessel: 'Tàu',
      voyage: 'Chuyến',
      pol: 'Cảng xếp',
      polPlaceholder: 'Cảng xếp hàng',
      pod: 'Cảng dỡ',
      podPlaceholder: 'Cảng dỡ hàng',
      origin: 'Điểm đi',
      destination: 'Điểm đến',
      etd: 'ETD',
      eta: 'ETA',
      atd: 'ATD',
      ata: 'ATA',
      actualDeliveryDate: 'Ngày giao thực tế',
      revenue: 'Doanh thu',
      cost: 'Chi phí',
      profit: 'Lợi nhuận',
      description: 'Mô tả',
      amount: 'Số tiền',
      backendProfitStatus: 'Trạng thái lợi nhuận',
      cannotVerify: 'Không thể xác minh từ frontend',
      missingJobId: 'Thiếu mã job.',
      loadError: 'Không thể tải job từ backend.',
      createSuccess: 'Đã tạo job.',
      createError: 'Không thể tạo job.',
      updateSuccess: 'Đã cập nhật job.',
      updateError: 'Không thể cập nhật job.',
      copySuccess: 'Đã sao chép job.',
      copyError: 'Không thể sao chép job.',
      cancelSuccess: 'Đã hủy job.',
      cancelError: 'Không thể hủy job.',
      jobTypeImport: 'Nhập khẩu',
      jobTypeExport: 'Xuất khẩu',
      jobTypeDomestic: 'Nội địa',
      shipmentSeaFcl: 'Đường biển FCL',
      shipmentSeaLcl: 'Đường biển LCL',
      shipmentAir: 'Hàng không',
      shipmentRoad: 'Đường bộ',
      shipmentRail: 'Đường sắt',
      statusDraft: 'Nháp',
      statusInProgress: 'Đang xử lý',
      statusClosed: 'Đã đóng',
      statusCancelled: 'Đã hủy',
      laneGreen: 'Xanh',
      laneYellow: 'Vàng',
      laneRed: 'Đỏ',
      cargoFcl: 'FCL',
      cargoLcl: 'LCL',
      cargoAir: 'Hàng không',
      cargoBulk: 'Hàng rời'
    },
    accountingForm: {
      postConfirm: 'Chốt bút toán nháp này?',
      postOk: 'Chốt',
      voidConfirm: 'Hủy bút toán kế toán này?',
      voidOk: 'Hủy',
      markCob: 'Đánh dấu chi hộ',
      cobTooltip: 'Chi hộ — tính phí khách hàng thay',
      posted: 'Đã chốt',
      openPayment: 'Đang chờ TT',
      draftItems: 'Bản nháp',
      searchPlaceholder: 'Tìm job, mô tả, trạng thái',
      noRecords: 'Không tìm thấy bút toán nào.',
      jobNo: 'Mã Job',
      jobRequired: 'Vui lòng chọn job.',
      selectJob: 'Chọn job',
      vendorAgent: 'NCC / Đại lý',
      vendorRequired: 'NCC là bắt buộc cho bút toán chi phí.',
      selectVendor: 'Chọn nhà cung cấp',
      description: 'Mô tả',
      descriptionRequired: 'Mô tả là bắt buộc.',
      descriptionPlaceholder: 'Mô tả bút toán',
      currency: 'Tiền tệ',
      currencyRequired: 'Tiền tệ là bắt buộc.',
      amount: 'Số tiền',
      amountRequired: 'Số tiền là bắt buộc.',
      exchangeRate: 'Tỷ giá',
      exchangeRateRequired: 'Tỷ giá là bắt buộc.',
      localAmount: 'Số tiền nội tệ',
      docDate: 'Ngày chứng từ',
      dueDate: 'Ngày đến hạn',
      refNumber: 'Số tham chiếu',
      refPlaceholder: 'Số tham chiếu',
      invoiceNumber: 'Số hóa đơn',
      invoicePlaceholder: 'Số hóa đơn',
      notes: 'Ghi chú',
      notesPlaceholder: 'Ghi chú',
      postSuccess: 'Đã chốt bút toán.',
      postError: 'Không thể chốt bút toán.',
      voidSuccess: 'Đã hủy bút toán.',
      voidError: 'Không thể hủy bút toán.',
      paymentUpdated: 'Đã cập nhật trạng thái thanh toán.',
      paymentError: 'Không thể cập nhật trạng thái thanh toán.',
      cobSuccess: 'Đã đánh dấu chi hộ. Phải thu tự động đã được tạo.',
      cobError: 'Không thể tạo khoản chi hộ.',
      cobDescription: 'Khi đánh dấu chi phí này là chi hộ, hệ thống sẽ tự tạo phải thu tương ứng từ khách hàng đã chọn, liên kết cùng mã Job.',
      selectCustomer: 'Chọn khách hàng'
    },
    filterCard: {
      search: 'Tìm kiếm',
      status: 'Trạng thái',
      dateRange: 'Khoảng ngày',
      reset: 'Đặt lại',
      searchPlaceholder: 'Tìm kiếm...'
    },
    statusTag: {
      active: 'Hoạt động',
      inactive: 'Ngừng HĐ'
    },
    timeAgo: {
      justNow: 'Vừa xong',
      minutesAgo: '{count} phút trước',
      hoursAgo: '{count} giờ trước',
      daysAgo: '{count} ngày trước'
    }
  }
};

const languageOptions = [
  { key: 'en', flag: 'US', emoji: 'US' },
  { key: 'vi', flag: 'VN', emoji: 'VN' }
];

const antdLocales = {
  en: enUS,
  vi: viVN
};

const LanguageContext = createContext(null);

function interpolate(text, params = {}) {
  return String(text).replace(/\{(\w+)\}/g, (_, key) => String(params[key] ?? ''));
}

function createTranslator(language) {
  return function translate(path, params) {
    const keys = path.split('.');
    let current = dictionary[language];

    for (const key of keys) {
      current = current?.[key];
    }

    if (!current) return path;
    return typeof current === 'string' ? interpolate(current, params) : current;
  };
}

export function AppProviders({ children }) {
  const [language, setLanguage] = useState('vi');

  useEffect(() => {
    const storedLanguage = window.localStorage.getItem(STORAGE_KEY);
    if (storedLanguage === 'en' || storedLanguage === 'vi') {
      window.setTimeout(() => setLanguage(storedLanguage), 0);
    }
  }, []);

  useEffect(() => {
    if (typeof window === 'undefined') return;
    window.localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const contextValue = {
    language,
    setLanguage,
    t: createTranslator(language),
    options: languageOptions
  };

  return (
    <StoreProvider>
      <AntdRegistry>
        <LanguageContext.Provider value={contextValue}>
          <ConfigProvider
            locale={antdLocales[language]}
            theme={{
              token: {
                colorPrimary: '#0057c2',
                colorBgBase: '#f9f9f9',
                colorBgContainer: '#ffffff',
                fontFamily: '"Inter", sans-serif',
                borderRadius: 4
              },
              components: {
                Button: {
                  colorPrimary: '#0057c2',
                  colorPrimaryHover: '#004398',
                  colorPrimaryActive: '#001a43'
                }
              }
            }}
          >
            {children}
          </ConfigProvider>
        </LanguageContext.Provider>
      </AntdRegistry>
    </StoreProvider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within AppProviders.');
  }
  return context;
}
